### ISSUE TITLE
自定义数据集的使用

### ISSUE THREAD

**Issue by Barryalana** [jp-lan/ProContEXT#10]
您好，
如果我需要使用自己的资料集来训练ProContEXT，请问我只需要准备影像资料以及对应的groundtruth.txt可以? 举例格式如下

-- dataset
     -- 我的训练资料集
         |-- 类1
              |-- Image1.jpg
              |-- Image2.jpg
              ...
              |-- groundtruth.txt
         |-- 类2
         |-- 类3
         ...
有其他资料是需要准备的吗？
(以got10K为例，它每类资料夹内有包含absence.label、cover.label、cut_by_image.label以及meta_info.ini等其他四项资料)
谢谢

**Comment by jp-lan** [comment]
可以的，自定义数据集可以完全按照got10k的标准数据来准备即可。

**Comment by Barryalana** [comment]
你好，我按照上面的格式进行了训练可总是提示我缺少absence.label文件，有这种只包含groundtruth的dataset模板的吗？
我按照如下格式引入的
object
  --train
	  --bike
		  --001.jpg
		  --002.jpg
		  ...
		  --groundtruth.txt
  --val
	  --car
		  --001.jpg
		  --002.jpg
		  ...
		  --groundtruth.txt

结果如下：
  File "/home/pony/ProContEXT/ProContEXT-main/lib/train/../../lib/train/dataset/got10k.py", line 157, in get_sequence_info
    visible, visible_ratio = self._read_target_visible(seq_path)
  File "/home/pony/ProContEXT/ProContEXT-main/lib/train/../../lib/train/dataset/got10k.py", line 139, in _read_target_visible
    with open(occlusion_file, 'r', newline='') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/pony/ProContEXT/ProContEXT-main/uav123gai/train/bike3/absence.label'


Restarting training from last epoch ...
Finished training!

进程已结束，退出代码为 0

总是显示的是缺少absence.label的文件。。请问该怎么解决，个人也尝试了按照其他的结构来但总是有问题，实在是不知道该如何是好了，望作者能帮忙看下指个方向，在此谢过！

**Comment by jp-lan** [comment]
这个absence.label是got10k数据集的标注格式，如果要使用该数据集的加载方式，请完全参照got10k的数据集来构造你的训练原始数据，具体可参考got10k的官方数据说明（http://got-10k.aitestunion.com/downloads 可以下载got10k的数据集后进行参照修改自己的数据） 。
![Uploading image.png…]()

**Comment by Barryalana** [comment]
你好，我按照上面的格式进行了训练可总是提示我缺少absence.label文件，有这种只包含groundtruth的dataset模板的吗？
我按照如下格式引入的
object
  --train
	  --bike
		  --001.jpg
		  --002.jpg
		  ...
		  --groundtruth.txt
  --val
	  --car
		  --001.jpg
		  --002.jpg
		  ...
		  --groundtruth.txt

结果如下：
  File "/home/pony/ProContEXT/ProContEXT-main/lib/train/../../lib/train/dataset/got10k.py", line 157, in get_sequence_info
    visible, visible_ratio = self._read_target_visible(seq_path)
  File "/home/pony/ProContEXT/ProContEXT-main/lib/train/../../lib/train/dataset/got10k.py", line 139, in _read_target_visible
    with open(occlusion_file, 'r', newline='') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/pony/ProContEXT/ProContEXT-main/uav123gai/train/bike3/absence.label'


Restarting training from last epoch ...
Finished training!

进程已结束，退出代码为 0

总是显示的是缺少absence.label的文件。。请问该怎么解决，个人也尝试了按照其他的结构来但总是有问题，实在是不知道该如何是好了，望作者能帮忙看下指个方向，在此谢过！

**Comment by Barryalana** [comment]
好的十分地感谢！
