### ISSUE TITLE
About speed

### ISSUE THREAD

**Issue by kun-dragon** [jp-lan/ProContEXT#2]
Beautiful work! I bet that the tracker will appear in the 2023ICCV.
I have roughly read your paper in the arXiv website. And I have a question:
What device is used to evaluate the speed of the tracker? One NVIDIA A100 GPU?

**Comment by jp-lan** [comment]
Thanks for following our work. We use NVIDIA A100 GPU to evaluate the speed of the tracker. BTW,  our paper is accepted by ICASSP 2023.
