### ISSUE TITLE
关于多尺度的问题

### ISSUE THREAD

**Issue by Anima1023** [jp-lan/ProContEXT#4]
作者您好，请问在ProContEXT训练中，这个多尺度静态模板部分是否在train中起作用，目前我只在test中找到这部分的相关因子等，如果在训练中也起作用的话，能否帮忙指出该部分代码，感谢。

**Comment by jp-lan** [comment]
你好，训练中也会使用多尺度的静态模板。
1. 多尺度的参数设置：https://github.com/jp-lan/ProContEXT/blob/401165b7c4bc2a7469e051160df90f2baba9ded9/experiments/procontext/procontext.yaml#L21
2. 训练时会根据这个函数进行多尺度模板获取: https://github.com/jp-lan/ProContEXT/blob/401165b7c4bc2a7469e051160df90f2baba9ded9/lib/train/data/processing_utils.py#L146

**Comment by Anima1023** [comment]
找到了 感谢！

**Comment by Anima1023** [comment]
作者您好 不好意思又打扰了 请问动态模板相关的实现有写在train中的部分吗 还是主要只在test-tracker下 如果我希望在您的基础上尝试改变动态模板机制的话请问我应该主要关注哪些部分呢？希望能大致指点一下 感谢
