### ISSUE TITLE
训练时弹出提示

### ISSUE THREAD

**Issue by minami-WYL** [jp-lan/ProContEXT#6]
e = Input and output sizes should be greater than 0, but got input (H: 0, W: 175) output (H: 128, W: 128)

**Comment by minami-WYL** [comment]
Did anyone see these during training？

**Comment by jp-lan** [comment]
It seems that the size of the input image patch is 0. Please make sure that you use the correct input data.

**Comment by HopeZ123** [comment]
I got the same errors during training. The code is the original code without changing. The data paths are correct. Does anyone know what is the reason for this?
