### ISSUE TITLE
Question about model flops and parameters

### ISSUE THREAD

**Issue by HopeZ123** [jp-lan/ProContEXT#8]
May I ask how did you measure the flops for the model procontext? Did you use the default tracking/profile_model.py? I tried with that, it shows the flop is about 48.318G with a pruning keep ratio of 0.7. I have no idea why it shows 38.0G when the keep ratio is 0.7. Even the fastest OSTrack has the flop of 48.3G when the keep ratio is 0.7. Procontext uses 4 templates, which creats 4 times of template tokens. I have no idea why the flop is smaller than OSTrack. Can you explain?

**Comment by jp-lan** [comment]
Are you comparing the result under the same resolution? The flops data in the paper is evaluated under the resolution of 256.

**Comment by HopeZ123** [comment]
That makes sense. Thank you so much. May I ask how did you make sure that the 2 dynamic templates are in the same size (192) when the template factors are different. Did you rescale the target size to mask sure the cropping sizes are the same? I could not find any code on this, can you explain a littile bit? Thank you so much.

**Comment by jp-lan** [comment]
We do rescale dynamic templates to the same size. You can delve into the following code to find more details: 
https://github.com/jp-lan/ProContEXT/blob/main/lib/test/tracker/procontext.py#L108

**Comment by HopeZ123** [comment]
Thank you so much!
