### ISSUE TITLE
Question about the speed of the model

### ISSUE THREAD

**Issue by HopeZ123** [jp-lan/ProContEXT#9]
Dear Authors,

Thank you for the brilliant work. I have a question about the speed since you mentioned that "ProContEXT can perform context encoding and tracking in real-time at 54.3 FPS." May I ask how did you measure this speed? Can you provide the code for measuring the speed? Thank you so much!

**Comment by jp-lan** [comment]
We mainly measure the inference time of the ProContEXT forward function (https://github.com/jp-lan/ProContEXT/blob/main/lib/models/procontext/procontext.py#L40C9-L40C16). You can measure the time cost of this line (https://github.com/jp-lan/ProContEXT/blob/main/lib/test/tracker/procontext.py#L92) using A100 GPU.

**Comment by HopeZ123** [comment]
I will try it. Thank you so much for the information.
